# Generated by Django 3.2.15 on 2022-08-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='image',
            new_name='playerimage',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='playername',
        ),
    ]
